### ISSUE TITLE
Suggestions gateway integration

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/graphql_gateway#45]
## Requirement
- https://github.com/IT-REX-Platform/content_service/issues/52

## Description
Integrate the suggestions in the gateway.

## Acceptance Criteria
- [ ] frontend can use it

**Comment by PaulBredl** [comment]
@myluki2000 when you do this, dont just query all chapters of a couse, but maybe use a filter to check that the chapter end date is after today and the start date is before today
